- name: Deploy Media Server
  hosts: all
  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
  tasks:
    - name: Update all apt packages
      ansible.builtin.apt:
        update_cache: true
    - name: Install Libass Library required by FFMpeg for subtitle burning
      ansible.builtin.apt:
        name: libass-dev
        state: present
    - name: Install Nginx for streaming media files
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: Install FFMpeg for transcoding media files
      ansible.builtin.apt:
        name: ffmpeg
        state: present
    - name: Install Nginx Extras for MP4 streaming
      ansible.builtin.apt:
        name: nginx-extras
        state: present
    - name: Install Transmission for downloading torrents
      ansible.builtin.apt:
        name: transmission-cli
        state: present
    - name: Start Nginx Service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
    - name: Apply Nginx template
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        mode: '0644'
      notify: Restart Nginx
